version: "3"
services: 
    blog: 
        image: pod32g/pod32g.com
        expose: 
            - "5000"
    proxy:
        image: nginx:latest
        container_name: nginx
        volumes: 
            - ./nginx:/etc/nginx/conf.d
            -  /etc/letsencrypt/live/pod32g.com/fullchain.pem:/etc/letsencrypt/live/pod32g.com/fullchain.pem
            - /etc/letsencrypt/live/pod32g.com/privkey.pem:/etc/letsencrypt/live/pod32g.com/privkey.pem
        ports: 
            - 80:80
            - 443:443
        depends_on:
            - blog
    watchtower:
        container_name: 'watchtower'
        image: containrrr/watchtower
        command: --cleanup --label-enable
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock